Repository AY2122S1-CS2103T-T17-2/tp, pull requests merged in 2021-10, with the labels that each got.

#54 Modify Tag functionality
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/UniqueTutorList.java
  src/main/java/seedu/address/model/tag/LevelSubjectCode.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/tag/LevelSubjectCodeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorTest.java
  src/test/java/seedu/address/testutil/TutorBuilder.java
Labels: type.Task, priority.High

#73 Fixed a few nits in the user guide
  docs/UserGuide.md
Labels: documentation

#90 Add minor GUI changes
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/images/cli_icon.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Enhancement, priority.Low

#91 Add available commands and tags list to help page of application
  src/main/java/seedu/address/ui/CommandListModel.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/SubjectTagModel.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Story, priority.Medium

#97 Change User Guide to be in line with CLITutors' current implementation
  docs/UserGuide.md
Labels: documentation, type.Task

#99 Add tutor qualification to GUI
  src/main/java/seedu/address/model/person/Qualification.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/TutorCard.java
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/TutorListCard.fxml
Labels: type.Enhancement

#105 Update Developer and User Guide
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/screenshots/Add.png
  docs/images/screenshots/Clear.png
  docs/images/screenshots/Delete.png
  docs/images/screenshots/Edit.png
  docs/images/screenshots/Find.png
  docs/images/screenshots/Help.png
  docs/images/screenshots/List.png
  docs/images/screenshots/Main Window.png
  docs/images/screenshots/Match.png
  docs/images/tracing/LogicSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/UiManager.java
Labels: documentation, type.Task, hacktoberfest-accepted

#106 Minor fixes to Documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.High, hacktoberfest-accepted

#107 Update Developer Guide
  docs/DeveloperGuide.md
Labels: documentation
