Repository AY2122S1-CS2103T-T17-2/tp, pull requests merged in 2021-11, with the labels that each got.

#188 Fix bugs, add tests, update documentation
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/StudentTest.java
  src/test/java/seedu/address/model/person/TutorTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.BugFixes, type.Task, hacktoberfest-accepted

#192 Fix issues found in PE-D
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/UiLabelled.png
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: documentation, type.BugFixes, type.Task

#194 Update DG
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: documentation, type.Task, hacktoberfest-accepted

#190 Branch bug fixes
  docs/images/zihaooo9.png
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/parser/MatchCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/TagsContainTagPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/MatchCommandTest.java
  src/test/java/seedu/address/logic/parser/MatchCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/TagsContainTagPredicateTest.java
Labels: type.BugFixes, type.Task

#189 Branch add and filter error message changes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/PersonType.java
  src/main/java/seedu/address/model/person/Gender.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: documentation, type.Task

#196 Update UI to wrap name and remark
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentListCard.fxml
  src/main/resources/view/TutorListCard.fxml
Labels: type.BugFixes, type.Task

#197 Update Developer Guide and contribution list
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/UiLabelled.png
  docs/team/lemonsr.md
Labels: documentation

#195 Fix name
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Qualification.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/java/seedu/address/ui/TutorCard.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: type.Enhancement, type.BugFixes

#200 Updated PPP
  docs/team/zihaooo9.md
Labels: documentation

#199 Fix Phone
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/CliTutors.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/CliTutorsTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement, type.BugFixes

#203 Updated PPP
  docs/AboutUs.md
  docs/images/lemonsr.png
  docs/team/johndoe.md
  docs/team/kleonang.md
  docs/team/knotstoks.md
  docs/team/lemonsr.md
Labels: documentation, type.Task

#205 Update DG with manual testing for Edit
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, type.Task

#209 Fix Edit error for Invalid Indices
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.BugFixes, type.Task

#207 Fix bug with clear command
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/CliTutors.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: type.BugFixes

#211 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/diagrams/FindCommandSequenceDiagram.puml
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/diagrams/MatchCommandSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddCommandSequenceDiagram.png
  docs/images/EditCommandActivityDiagram.png
  docs/images/FindCommandSequenceDiagram.png
  docs/images/ListCommandSequenceDiagram.png
  docs/images/MatchCommandSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: documentation, type.Task

#210 Update UG
  docs/UserGuide.md
  docs/images/UiLabelled.png
  docs/images/screenshots/Help.png
Labels: documentation

#215 Fix spelling mistakes and typos for PPP
  docs/team/zihaooo9.md
Labels: documentation

#217 Update PPP
  docs/team/kleonang.md
Labels: documentation

#216 Improve code quality and coverage
  docs/team/tenebrius1.md
  src/main/java/seedu/address/commons/exceptions/DataConversionException.java
  src/main/java/seedu/address/commons/util/AppUtil.java
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/commons/util/ConfigUtil.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ChainedPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/commons/util/ConfigUtilTest.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/CliTutorsParserTest.java
  src/test/java/seedu/address/model/person/ChainedPredicateTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Task

#212 Improve test coverage
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/parser/MatchCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniqueTutorList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/CliTutorsParserTest.java
  src/test/java/seedu/address/model/CliTutorsTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/GenderTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/QualificationTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/model/person/StudentTest.java
  src/test/java/seedu/address/model/person/TutorTest.java
  src/test/java/seedu/address/model/person/UniqueStudentListTest.java
  src/test/java/seedu/address/model/person/UniqueTutorListTest.java
Labels: type.Enhancement

#214 Improve test code quality and Edit test coverage
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/images/EditCommandActivityDiagram.png
  docs/images/screenshots/Add.png
  docs/images/screenshots/Clear.png
  docs/images/screenshots/Delete.png
  docs/images/screenshots/Edit.png
  docs/images/screenshots/Filter_After.png
  docs/images/screenshots/Filter_Before.png
  docs/images/screenshots/Find.png
  docs/images/screenshots/Help.png
  docs/images/screenshots/List_After.png
  docs/images/screenshots/List_Before.png
  docs/images/screenshots/Main Window.png
  docs/images/screenshots/Match.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/commons/util/CollectionUtilTest.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/MatchCommandTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MatchCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/CliTutorsTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/TagsContainTagPredicateTest.java
  src/test/java/seedu/address/model/person/UniqueTutorListTest.java
  src/test/java/seedu/address/model/tag/LevelSubjectCodeTest.java
  src/test/java/seedu/address/storage/JsonAdaptedTutorTest.java
  src/test/java/seedu/address/testutil/CliTutorsBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TutorUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/UiPartTest.java
Labels: type.Task

#220 Improve Code quality
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Task

#218 Fix Qualification
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/QualificationContainsQualificationPredicate.java
  src/main/java/seedu/address/model/person/Student.java
  src/test/java/seedu/address/model/person/QualificationContainsQualificationPredicateTest.java
Labels: type.Task

#221 Replace screenshots
  docs/images/screenshots/Add.png
  docs/images/screenshots/Clear.png
  docs/images/screenshots/Delete.png
  docs/images/screenshots/Edit.png
  docs/images/screenshots/Filter_After.png
  docs/images/screenshots/Filter_Before.png
  docs/images/screenshots/Find.png
  docs/images/screenshots/Help.png
  docs/images/screenshots/List_After.png
  docs/images/screenshots/List_Before.png
  docs/images/screenshots/Main Window.png
  docs/images/screenshots/Match.png
Labels: documentation

#222 Trying to increase code coverage
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/EditStudentDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditTutorDescriptorTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/GenderTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/QualificationTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/model/person/StudentTest.java
  src/test/java/seedu/address/model/person/TutorTest.java
  src/test/java/seedu/address/model/person/UniqueStudentListTest.java
  src/test/java/seedu/address/model/person/UniqueTutorListTest.java
  src/test/java/seedu/address/model/tag/LevelSubjectCodeTest.java
  src/test/java/seedu/address/storage/JsonSerializableCliTutorsTest.java
  src/test/java/seedu/address/testutil/Assert.java
  src/test/java/seedu/address/testutil/CliTutorsBuilder.java
  src/test/java/seedu/address/testutil/EditStudentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TestUtil.java
Labels: type.Task

#226 Fix FindCommand bug
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.BugFixes, type.Task

#227 Fix FindCommand bug
  src/main/java/seedu/address/logic/commands/FindCommand.java
Labels: type.BugFixes, type.Task
