Repository AY2122S1-CS2103T-T17-2/tp, pull requests merged in 2021-09, with the labels that each got.

#28 Add user stories to Developer Guide
  docs/DeveloperGuide.md
  docs/_config.yml
Labels: documentation

#30 Update various documentations
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: documentation

#29 Update image path
  docs/AboutUs.md
Labels: documentation, bug fixes

#31 Update lemonsr.png
  docs/AboutUs.md
  docs/images/lemonsr.png
Labels: documentation, bug fixes

#47 Update user guide
  docs/UserGuide.md
Labels: documentation, type.Task
